### ISSUE TITLE
Exception when using snackbar while modal is open

### ISSUE THREAD

**Issue by izub** [nstudio/nativescript-snackbar#2]
I have a full screen modal where the user uploads a new picture. If the upload was successful, the modal is closed and a simple snackbar is shown. The snackbar displays without issues. But after the timeout has passed, the snackbar is automatically dismissed and the following exception is thrown:

```
An uncaught Exception occurred on "main" thread.
Calling js method onDismissed failed
TypeError: Cannot read property '_getReason' of null

StackTrace:
    Frame: function:'push.../node_modules/@nstudio/nativescript-snackbar/snackbar.js.TNS_SnackbarBaseCallback.onDismissed', file:'file:///node_modules/@nstudio/nativescript-snackbar/snackbar.js:184:0
    at com.tns.Runtime.callJSMethodNative(Native Method)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
    at com.tns.Runtime.callJSMethod(Runtime.java:1109)
    at com.tns.Runtime.callJSMethod(Runtime.java:1089)
    at com.tns.Runtime.callJSMethod(Runtime.java:1081)
    at com.google.android.material.snackbar.BaseTransientBottomBar_BaseCallback_vendor_113222_28_TNS_SnackbarBaseCallback.onDismissed(Unknown Source:27)
    at com.google.android.material.snackbar.BaseTransientBottomBar.onViewHidden(BaseTransientBottomBar.java:687)
    at com.google.android.material.snackbar.BaseTransientBottomBar$10.onAnimationEnd(BaseTransientBottomBar.java:625)
    at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
    at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
    at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
    at android.view.Choreographer.doCallbacks(Choreographer.java:723)
    at android.view.Choreographer.doFrame(Choreographer.java:655)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

The error also occurs when the modal is not closed. If I close the modal, then display the snackbar with a small delay (200ms), the exception is not thrown.

Using @nstudio/nativescript-snackbar 1.0.0, nativescript-angular 8.0.2, angular 8.1.2 and Android 8.0.0.

**Comment by yassern** [comment]
did u tried pass a view as parameter?

**Comment by surdu** [comment]
I see the same error in my Google Play reports and can't figure out how to reproduce it. My app has no modals.

@yassern From the documentation is not clear: the `view` option, is it used to indicate the parent view of the snackbar ?

**Comment by jscti** [comment]
I have the same error while I show a simple snackbar while the android soft keyboard opens or is already opened.

**Comment by jscti** [comment]
Well reproductibility is not 100% but it's clearly linked to the softkeyboard hiding/opening during snackbar show/stay/dismiss :/

**Comment by bradmartin** [comment]
@jscti  can you try `1.1.2-beta1` version just published? I changed the default root view to see if this improves it always being created at the rootview of the ViewGroup of the Android Activity (NativeScriptActivity).

**Comment by bradmartin** [comment]
correction, another change based on the stack in this issue made `1.1.2-beta2` now published :)

**Comment by bradmartin** [comment]
@surdu also curious if you can try the beta out and see if it functions better. I moved the `_getReason` method out of the class and the demo apps function fine with this. I'm assuming this will help with the case where the `owner` was failing to return a value in the previous callback implementation. Now the callback just calls the function directly without worry of the `reference` so hopefully this remedies the issues.

**Comment by bradmartin** [comment]
If someone can confirm this works fine and possibly improves the crashes, I'll go ahead & publish. Thanks

**Comment by jscti** [comment]
I'm on it. beta1 = crash.
Testing beta2

**Comment by jscti** [comment]
Beta2 seems OK ! :) Well made !

**Comment by surdu** [comment]
I will put it in my builds and see if it goes away from the crash reports! Thanks @bradmartin !

**Comment by bradmartin** [comment]
@jscti @surdu  thanks for replying, since @jscti is seeing improvements, I'll go ahead and publish 1.1.2 so those not seeing this can get the bug fix 💯  , feel free to ping me here @surdu if still having any weird issues or crash reports around this.

**Comment by jscti** [comment]
Just sayin but :

I keep struggling on nativescript issues opened in 2016 and still not closed every days
And you ... you just fix and close issues in less than an hour  ...
You deserve an award ! :+1: 
Nativescript needs you ^^

**Comment by bradmartin** [comment]
Good and bad sometimes, I like to move fast, sometimes it breaks things, but I've found that less overhead and  "chore" related work to fixing issues works better most of the time 😄. I'd also rather code and try to fix something than type out long messages, fill out reports, detail stuff, etc. 😆  

Not the best, but seems to work well majority of the time.

Thanks for the kind remarks.
